E2Helper.Descriptions["runOnCollision(en)"] = "If set to 1, E2 will run when specified entity collides"
E2Helper.Descriptions["collideClk()"] = "Returns 1 if the chip execution was caused by collision"
E2Helper.Descriptions["getCollision(xcl:)"] = "Returns the collision data from the last collision"
E2Helper.Descriptions["hitPos(xcl:)"] = "Returns the collision position"
E2Helper.Descriptions["hitEntity(xcl:)"] = "Returns the entity that we collide with"
E2Helper.Descriptions["ourEntity(xcl:)"] = "Returns the entity that collides"
E2Helper.Descriptions["ourOldVel(xcl:)"] = "Returns the entity's velocity before the collision"
E2Helper.Descriptions["theirOldVel(xcl:)"] = "Returns speed of the other entity before the collision"
E2Helper.Descriptions["delta(xcl:)"] = "Returns time since the last collision with this HitEntity"
E2Helper.Descriptions["speed(xcl:)"] = "Returns the speed of the entity before the collision"
E2Helper.Descriptions["hitNormal(xcl:)"] = "Returns normal of the surface that hit the other entity"
E2Helper.Descriptions["toTable(xcl:)"] = "Converts collision data to table"

E2Helper.Descriptions["pos(xcl:)"] = "Deprecated, xcl:hitPos should be used instead"
E2Helper.Descriptions["entity(xcl:)"] = "Deprecated, xcl:hitEntity should be used instead"
E2Helper.Descriptions["normal(xcl:)"] = "Deprecated, xcl:hitNormal should be used instead"
