E2Helper.Descriptions["runOnCollision(en)"] = "If set to 1, the chip will run when the specified entity collides with anything"
E2Helper.Descriptions["collideClk()"] = "Returns 1 if the chip execution was caused by a collision"
E2Helper.Descriptions["getCollision()"] = "Returns the collision data from the last collision"
E2Helper.Descriptions["hitPos(xcl:)"] = "Returns the collision position"
E2Helper.Descriptions["hitEntity(xcl:)"] = "Returns the other collision entity"
E2Helper.Descriptions["ourEntity(xcl:)"] = "Returns the collision entity"
E2Helper.Descriptions["ourOldVel(xcl:)"] = "Returns the entity's velocity before the collision"
E2Helper.Descriptions["theirOldVel(xcl:)"] = "Returns the other entity's velocity before the collision"
E2Helper.Descriptions["delta(xcl:)"] = "Returns the time since the last collision with the other entity"
E2Helper.Descriptions["speed(xcl:)"] = "Returns the speed of the entity before the collision"
E2Helper.Descriptions["hitNormal(xcl:)"] = "Returns the normal of the surface that hit the other entity"
E2Helper.Descriptions["toTable(xcl:)"] = "Returns the collision data as a table"

E2Helper.Descriptions["pos(xcl:)"] = "Deprecated, xcl:hitPos should be used instead"
E2Helper.Descriptions["entity(xcl:)"] = "Deprecated, xcl:hitEntity should be used instead"
E2Helper.Descriptions["normal(xcl:)"] = "Deprecated, xcl:hitNormal should be used instead"
